using System.Collections.Generic;

namespace MegabonkTogether.Services
{
    public enum SteamLobbyState
    {
        /// <summary>Not in a lobby and not trying to be.</summary>
        None,

        /// <summary>A create or join call is in flight, waiting on its result.</summary>
        Pending,

        /// <summary>In a lobby. <see cref="ISteamLobbyService.LobbyId"/> is valid.</summary>
        InLobby,

        /// <summary>The last operation failed. <see cref="ISteamLobbyService.DescribeStatus"/> says how.</summary>
        Failed,
    }

    /// <summary>Where a lobby-list search has got to. Independent of lobby membership.</summary>
    public enum SteamLobbySearchState
    {
        Idle,
        Searching,

        /// <summary>Finished. <see cref="ISteamLobbyService.FoundLobbyId"/> is 0 if nothing matched.</summary>
        Completed,

        Failed,
    }

    /// <summary>
    /// Steam lobbies: create, join, leave, and the key/value data hung off them.
    ///
    /// <para>Phase 3 of the Steamworks migration. This does not yet replace the WebSocket
    /// matchmaker — nothing in the game flow calls it. It exists so the primitives underneath can
    /// be exercised and proved before the lobby flow is moved onto them.</para>
    ///
    /// <para><b>No callbacks anywhere.</b> `Callback&lt;T&gt;` and `CallResult&lt;T&gt;` have
    /// concrete IL2CPP instantiations only for the six type arguments the game itself uses, and
    /// none of them is a lobby type — so asynchronous results are polled instead. See
    /// <c>docs/steamworks/00-migration-plan.md</c>, "Phase 3 does not need generics at all".</para>
    /// </summary>
    public interface ISteamLobbyService
    {
        SteamLobbyState State { get; }

        /// <summary>
        /// Whether a Steam call is in flight. The ticker polls every frame while this is true,
        /// because the result has to be read before the game's callback pump frees it.
        /// </summary>
        bool HasPendingCall { get; }

        SteamLobbySearchState SearchState { get; }

        /// <summary>The lobby the last search found, or 0 if it found nothing.</summary>
        ulong FoundLobbyId { get; }

        /// <summary>The current lobby, or 0.</summary>
        ulong LobbyId { get; }

        /// <summary>
        /// The short code for the current lobby, or empty. Generated by the host and read from
        /// lobby data by everyone else, so both ends report the same thing.
        /// </summary>
        string LobbyCode { get; }

        /// <summary>
        /// The lobby Steam asked us to join on the command line, or 0. Set once at construction.
        ///
        /// <para>This is how accepting a friend's invite arrives when the game was <b>closed</b>.
        /// Accepting one while the game is already running produces a
        /// <c>GameLobbyJoinRequested_t</c> callback instead, which this install cannot receive —
        /// see the remarks on the implementation.</para>
        /// </summary>
        ulong LaunchLobbyId { get; }

        /// <summary>Whether the local player owns the current lobby. False when not in one.</summary>
        bool IsOwner { get; }

        /// <summary>
        /// Starts creating a private lobby. Asynchronous: <see cref="State"/> goes to
        /// <see cref="SteamLobbyState.Pending"/> and <see cref="Poll"/> resolves it.
        /// </summary>
        void CreateLobby(int maxMembers);

        /// <summary>
        /// Starts joining an existing lobby by id. Asynchronous, same as
        /// <see cref="CreateLobby"/>.
        ///
        /// <para>On entry the lobby's published protocol version is checked, and a lobby that does
        /// not match is left again with <see cref="State"/> set to
        /// <see cref="SteamLobbyState.Failed"/>. The check happens after entering because lobby
        /// metadata is only readable to a member — see the remarks on the implementation.</para>
        /// </summary>
        void JoinLobby(ulong lobbyId);

        /// <summary>
        /// Finds a lobby by its short code and joins it. Asynchronous, and two Steam calls deep:
        /// a filtered lobby-list search, then a join.
        ///
        /// <para>The search filters on protocol version as well as the code, so a lobby hosted by
        /// an incompatible build is simply absent from the results.</para>
        /// </summary>
        void JoinByCode(string code);

        /// <summary>
        /// Joins the Steam lobby standing for a matchmaker room, found by that room's code.
        ///
        /// <para>How a client that typed a room code — and so never saw a Steam lobby id — ends up
        /// in the same Steam lobby as its host. Silent about failure: the session works without it,
        /// and only the extras hung off the Steam lobby are lost.</para>
        /// </summary>
        void JoinByMatchmakerCode(string code);

        /// <summary>
        /// Searches for a lobby by code <b>without joining it</b>, leaving the result in
        /// <see cref="FoundLobbyId"/>. Usable while already in a lobby, which is what lets the
        /// discovery path be checked at all without a second player — and what a lobby browser
        /// will want.
        /// </summary>
        void FindLobbyByCode(string code);

        /// <summary>
        /// Opens Steam's own invite dialog for the current lobby. No-op outside a lobby.
        ///
        /// <para>Nothing comes back through this: the invite, the friend list and the accept flow
        /// all belong to Steam.</para>
        /// </summary>
        void OpenInviteOverlay();

        /// <summary>Leaves the current lobby, if any. Safe to call when not in one.</summary>
        void LeaveLobby();

        /// <summary>
        /// Drives any in-flight call and keeps the member list current. Cheap and re-entrant-safe
        /// when idle, but it is native calls — drive it from an accumulator, not every frame.
        /// </summary>
        void Poll();

        bool SetLobbyData(string key, string value);

        string GetLobbyData(string key);

        /// <summary>
        /// Writes one of the local player's own member-data rows. Steam only lets a member write
        /// its own row, which is why host authority over readiness stops being ours to enforce.
        /// </summary>
        bool SetLocalMemberData(string key, string value);

        string GetMemberData(ulong steamId, string key);

        /// <summary>Members of the current lobby, empty when not in one.</summary>
        IReadOnlyList<ulong> GetMembers();

        string DescribeStatus();
    }
}
